### ISSUE TITLE
Compile [out] option

### ISSUE THREAD

**Issue by Toilal** [gabegorelick/gulp-angular-gettext#13]
I'm migrating from angular-gettext from grunt to gulp. I can't find a way using this gulp plugin to compile to a single file for every languages `*.po` files.

Here's my grunt configuration that creates a single file `app/scripts/translations.js`

    nggettext_compile: {
      all: {
          options: {
              module: 'ttpApp'
          },
          files: {
              'app/scripts/translations.js': ['po/*.po']
          }
      }
    },

Maybe an [out] option could be implemented, like for extract task ?

**Comment by gabegorelick** [comment]
Copying my comments from #12 since this is a better place to discuss this:

>What exactly is the use case for concatting the JSON/JS output? Do you have multiple PO files you want to combine?
>
>Also, concatting JSON/JS is kind of orthogonal to this plugin. I only added that feature to extract since a naive concat with something like gulp-concat will generate incorrect PO files.

**Comment by Toilal** [comment]
Yes, i have one PO file per language (5 supported langages for my app, so 5 PO file in my case), and want a single javascript file with each language defined in a single module.

PR #12 contains also changes for #3, maybe you wan't me to rebase those changes on current master in a  new PR ? Maybe you wan't 2 differents PR for #3 and #14 ?

**Comment by gabegorelick** [comment]
> Yes, i have one PO file per language (5 supported langages for my app, so 5 PO file in my case), and want a single javascript file with each language defined in a single module.

OK, that seems reasonable. Is there any way to achieve that using existing gulp plugins, e.g. with something like https://www.npmjs.com/package/gulp-extend?

> PR #12 also contains changes for #3, maybe you wan't me to rebase those changes on current master in a new PR ? Maybe you want 2 differents PR for #3 and #14 ?

Yes, if you could send separate PRs for each feature, that's much easier to review and integrate. Thanks.

**Comment by Toilal** [comment]
Please note i don't use `json` output, but `js` output. For `json` output, it should work with gulp-extend plugin.

But for javascript output, using gulp-concat plugin won't work, because it will declared the same module multiple times.

hen generating multiple javascript files, importing them in the same project would result in a module beeing declared multipled times. 

(that beeing said, it's not possible to import multiple language files too, because each language files have the same module name. Maybe there should be an option to declare a different module name for each language in this case, but it could be discussed later in another issue ...)

I'll make 2 new PR for those features (#3 & #14) in the evening.

**Comment by gabegorelick** [comment]
> But for javascript output, using gulp-concat plugin won't work, because it will declared the same module multiple times

Yeah, I believe this has been brought up before upstream. My general recommendation is to output JSON from {gulp,grunt}-angular-gettext and then post-process it to generate JS that meets your needs. It's really not hard since all the javascript format does is wrap the JSON in a few lines of angular boilerplate. That would also solve your duplicate module name problem, since you can output JS that instantiates whatever modules you want.

Some gulp plugins that might help you out generating your JS:
* https://www.npmjs.com/package/gulp-header
* https://www.npmjs.com/package/gulp-footer
* https://www.npmjs.com/package/gulp-wrapper

**Comment by Toilal** [comment]
Thanks for you recommandations ! 

FYI, i'm currently working on yeoman [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular) that will ask user to use a translation module when generating the project skeleton, [angular-gettext](https://angular-gettext.rocketeer.be/) or [angular-translate](https://github.com/angular-translate/angular-translate).

**Comment by Toilal** [comment]
@gabegorelick I finally done the work required.

I've used [gulp-wrap](https://github.com/adamayres/gulp-wrap) and [gulp-extend](https://github.com/adamayres/gulp-extend) plugin, but I need to make a PR (https://github.com/adamayres/gulp-wrap/pull/17) to be able to change the template engine, because current engine `lodash.template` doesn't support `_.forEach` function. (only `_.template` from full lodash module supports this).

So when the PR from gulp-wrap will be merged, here's the kind of configuration we could have in the README.

```js
'use strict';

var gulp = require('gulp');
var $ = require('gulp-load-plugins')();

paths = {
    src: 'src',
    tmp: '.tmp',
}

gulp.task('translate:compile', function () {
  return gulp.src(paths.src + '/gettext/**/*.po')
    .pipe($.angularGettext.compile({format: 'json'}))
    .pipe($.extend('translations.json')) // use .json extension for wrap plugin to load content
    .pipe($.wrap(
      '\'use strict\';\n\n' +
      'angular.module(\'ticTacPlanning\').run([\'gettextCatalog\', function (gettextCatalog) {\n' +
      '/* jshint -W100,-W109 */\n' +
      '<% _.forEach(contents, function(translations, lang) { %>  gettextCatalog.setStrings(\'<%= lang %>\', <%= JSON.stringify(translations, undefined, 2) %>);\n<% }); %>' +
      '/* jshint +W100,+W109 */\n' +
      '}]);'))
    .pipe($.rename('translations.js')) // rename to javascript
    .pipe(gulp.dest(paths.tmp + '/serve/translations/'));
});
```

output something like this

```js
'use strict';

angular.module('ticTacPlanning').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100,-W109 */
  gettextCatalog.setStrings('de', {
  "Choose a password": "Choisissez un mot de passe",
  "Confirm your password": "Confirmez votre mot de passe",
  "Create Account": "Créer un compte",
  "E-mail": "E-mail",
  "Password": "Mot de passe",
  "Please apologize for the inconvenience, and try again later": "Veuillez nous excuser pour la gêne occasionnée, et essayez à nouveau plus tard",
  "Please check your e-mail and password, and try again": "Veuillez vérifier votre e-mail et votre mot de passe, puis essayer à nouveau",
  "Please use another e-mail, or try to sign in with your existing account": "Veuillez utiliser un autre e-mail, ou essayer de vous connecter avec votre compte existant",
  "Sign In": "Se connecter",
  "Sign Out": "Se déconnecter",
  "The e-mail or password doesn't match our files": "L'email et le mot de passe ne correspondent pas à nos fichiers",
  "The two passwords doesn't match": "Les deux mots de passe ne correspondent pas",
  "This e-mail already exists in our files": "L'email existe déjà dans nos fichiers",
  "This field is not a valid e-mail": "Ce champ n'est pas un e-mail valide",
  "This field is required": "Ce champ est obligatoire",
  "TicTac Planning": "TicTac Planning",
  "Your e-mail address": "Votre adresse e-mail",
  "has encountered an unkown error": "a rencontré une erreur inconnue",
  "is currently out of order": "est actuellement hors-service",
  "Créer un compte": "aze",
  "Se connecter": "azeaze",
  "Se déconnecter": "azeazeaze"
});
  gettextCatalog.setStrings('fr', {
  "Choose a password": "Choisissez un mot de passe",
  "Confirm your password": "Confirmez votre mot de passe",
  "Create Account": "Créer un compte",
  "E-mail": "E-mail",
  "Password": "Mot de passe",
  "Please apologize for the inconvenience, and try again later": "Veuillez nous excuser pour la gêne occasionnée, et essayez à nouveau plus tard",
  "Please check your e-mail and password, and try again": "Veuillez vérifier votre e-mail et votre mot de passe, puis essayer à nouveau",
  "Please use another e-mail, or try to sign in with your existing account": "Veuillez utiliser un autre e-mail, ou essayer de vous connecter avec votre compte existant",
  "Sign In": "Se connecter",
  "Sign Out": "Se déconnecter",
  "The e-mail or password doesn't match our files": "L'email et le mot de passe ne correspondent pas à nos fichiers",
  "The two passwords doesn't match": "Les deux mots de passe ne correspondent pas",
  "This e-mail already exists in our files": "L'email existe déjà dans nos fichiers",
  "This field is not a valid e-mail": "Ce champ n'est pas un e-mail valide",
  "This field is required": "Ce champ est obligatoire",
  "TicTac Planning": "TicTac Planning",
  "Your e-mail address": "Votre adresse e-mail",
  "has encountered an unkown error": "a rencontré une erreur inconnue",
  "is currently out of order": "est actuellement hors-service",
  "Créer un compte": "aze",
  "Se connecter": "azeaze",
  "Se déconnecter": "azeazeaze"
});
/* jshint +W100,+W109 */
}]);
```

**Comment by gabegorelick** [comment]
Cool. There might be alternatives to gulp-wrap that already work. That was
just one that popped up first. But anyway, I'll add something to the README
when it's done.

**Comment by Toilal** [comment]
I didn't find anything really better. It will be great after the merge of this PR, beeing able to use any kind of template engine ! (jade, handlebars, ...)

I'll let you know when it's merged, with my final tested configuration for the README.

**Comment by Toilal** [comment]
Hi @gabegorelick here's the final gulp script. It works with actual version of `gulp-wrap` plugin, because i've removed usage of lodash `_.forEach`, replaced by native implementation.

```js
var gulp = require('gulp');

var angularGettext = require('gulp-angular-gettext');
var extend = require('gulp-extend');
var wrap = require('gulp-wrap');
var rename = require('gulp-rename');

gulp.task('gettext:compile', function() {
  return gulp.src('src/po/*.po') // Stream PO translation files.
    .pipe(angularGettext.compile({format: 'json'})) // Compile to json
    .pipe(extend('.tmp.json')) // use .json extension for gulp-wrap to load json content
    .pipe(wrap( // Build the translation module using gulp-wrap and lodash.template
      '\'use strict\';\n\n' +
      'angular.module(\'myApp\').run(function (gettextCatalog) {\n' +
      '/* jshint -W100,-W109 */\n' +
      '<% var langs = Object.keys(contents); var i = langs.length; while (i--) {' +
      'var lang = langs[i]; var translations = contents[lang]; %>'+
      '  gettextCatalog.setStrings(\'<%= lang %>\', <%= JSON.stringify(translations, undefined, 2) %>);\n'+
      '<% }; %>' +
      '/* jshint +W100,+W109 */\n' +
      '});'))
    .pipe(rename('gettext.catalog.js')) // Rename to final javascript filename
    .pipe(gulp.dest('src/scripts/')); // output to "src/scripts" directory
});
```

**Comment by mchlbrnd** [comment]
Awesome @Toilal! Just when I needed to bundle all translations in one file. :)

One problem in your template. You forgot to add 'gettext' as a module dependency for module 'myApp' for injection of gettextCatalog to work.

Any plans for a PR?

**Comment by Toilal** [comment]
just replace `myApp` with the name of your application module. This sample doesn't declare this file in another module.

**Comment by mchlbrnd** [comment]
Ah, ofcourse. I namespace my modules. That's why. :)

**Comment by Toilal** [comment]
so just change `myApp` to `myApp.translations`. And then declare it as a dependency in your main module.

    angular.module('myApp', [..., ..., 'myApp.translations']);

In fact it won't be integrated in this plugin, but this snippet will probably be included in the readme.

**Comment by gabegorelick** [comment]
Glad this worked out. Feel free to send me a PR to update the README if I don't get around to it soon.
