### ISSUE TITLE
Make json the default format

### ISSUE THREAD

**Issue by Toilal** [gabegorelick/gulp-angular-gettext#17]
Maybe it would be better to have `{format: 'json'}` as the default options object for `compile` function.

As you have said @gabegorelick in #13, it's really more efficient and natural in gulp environment to use this format as default instead of `javascript`.

**Comment by gabegorelick** [comment]
I agree that `format: 'json'` is vastly superior to `format: 'javascript'`, but I don't want to diverge with what angular-gettext-tools does. This plugin should be as minimal a wrapper around angular-gettext-tools as possible.

**Comment by gabegorelick** [comment]
FYI there's a PR open upstream to at least make the docs a little better in this respect: https://github.com/rubenv/angular-gettext-tools/pull/72
