### ISSUE TITLE
gulp-angular-gettext does not create any content in target .pot file

### ISSUE THREAD

**Issue by clue42** [gabegorelick/gulp-angular-gettext#20]
Hi,
using the example config I have not been able to create any content in the target .pot file. The .pot file is more or  less empty:

msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Project-Id-Version: \n"

the test input in JADE looks like this:

h2(translate) hometranslation
p {{home.ctrlName}}
translate Test
input(type='text', placeholder="{{'Username' | translate}}")

any idea on this?

thanks

**Comment by gabegorelick** [comment]
Are you running it against JADE files? That probably won't work. You want to convert your JADE into HTML first and then run it.

**Comment by clue42** [comment]
Right, it seems I have mistaken one of the closed issues as confirmation of the parsing support for JADE files, which by revisiting the issue seems not to be the case.  Parsing HTML works perfectly fine. 
thanks, anyway
