### ISSUE TITLE
Preserve existing translated keys

### ISSUE THREAD

**Issue by lionelB** [gabegorelick/gulp-angular-gettext#22]
Hello,

I may have missed something but how  do you handle iterative worflow ?
Is there a way to generate POT files while keeping already existing keys from a given PO file ?
Each time I generate a pot file, I have a blank file so I need to manually merge my existing po file with that new one which is painfull :(

**Comment by gabegorelick** [comment]
Msgmerge:
https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html

Also, platforms like transifex will handle the merging for you.

**Comment by lionelB** [comment]
OH thanks !

**Comment by thiagoalvernaz** [comment]
Also had the same problem, I solved a not very beautiful,
But solves my life rsrsrs look:

```
function potMerge(file, merge) {
  file  = fs.readFileSync(file).toString();
  merge = fs.readFileSync(merge).toString();
  file  = file.split(/[\r\n]/);
  merge = merge.split(/[\r\n]/);

  // get msgid
  var mergeMsgidList = [];
  merge.filter(function(index, elem) {
    if(index.indexOf("msgid")===0){
      mergeMsgidList[index.split('"')[1]] = merge[elem+1].split('"')[1];
    }
  });

  var newText;
  // merge files
  file.map(function(index, elem) {
    if(index.indexOf("msgid")===0){
      if(mergeMsgidList[index.split('"')[1]]!=undefined){
        newText = 'msgstr "'+mergeMsgidList[index.split('"')[1]]+'"';
        file[elem+1] = newText;
      }
    }
  });

  file = file.join('\n');

  fs.writeFile('buildTemplate.po', file, function (err) {
    if(err) throw err;
    console.log('Merge with success');
  });
}
```

**Comment by lionelB** [comment]
Here is a workflow based on poEdit.
first, you need generate pot file, import it in poEdit and save to lang.po file.  
then each time you need to update your po files.
- generate a pot file
- open a po file in poedit, 
- proceed to a "catalog > update from a POT" 

PoEdit will handle the merge automatically.
