### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gunta** [gabegorelick/gulp-angular-gettext#24]
Hi!

When installing gulp-angular-gettext one gets deprecated warnings.
`npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'`

It comes from `angular-gettext-tools` which in turn comes from `cheerio`. 
So updating the dependencies should solve the problem.

Thank you!

**Comment by gabegorelick** [comment]
Thanks. I'll work with upstream to update their deps. Thanks to semver we shouldn't have to do anything here.
