### ISSUE TITLE
Very strange bug with multiple attributes

### ISSUE THREAD

**Issue by mewis** [gabegorelick/gulp-angular-gettext#27]
Hey I have come across a very strange bug when using multiple attributes. I have a switch directive, within this I have a on attribute and a off attribute (what text  to display when the switch is on and off).

If I have the attributes next to each other

<switch class="small" 
             checked="focused.settings.require
             off="'global.no' | translate"
             on="'global.yes' | translate"
                                ></switch>

gulp-angular-gettext does not see the second attribute

#: journal/single.html:57
msgid "global.no"
msgstr ""

but if I have a attribute in between the two it does

<switch class="small" 
             off="'global.no' | translate"
             checked="focused.settings.require
             on="'global.yes' | translate"
                                ></switch>

#: journal/single.html:57
msgid "global.no"
msgstr ""

#: journal/single.html:57
msgid "global.yes"
msgstr ""

Is there a problem with multiple translated attributes in one element?

**Comment by gabegorelick** [comment]
I recommend filing a bug against https://github.com/rubenv/angular-gettext-tools unless you think this is related to the gulp plugin. I do know there are already a bunch of issues filed upstream about extracting attributes/filters.
