### ISSUE TITLE
Relative references by default

### ISSUE THREAD

**Issue by gabegorelick** [gabegorelick/gulp-angular-gettext#3]
Currently, the file references for a POT entry are absolute, e.g. `/home/gabe/foo/src/partial.html`. But that causes a lot of churn when the POT is checked into version control, since everyone's paths are different.

In all my client code, including the tests cases, I manually make the file references relative to the directory the POT file is written to. That won't work in gulp because the plugin doesn't know where you will output the POT file (that's handled later in the pipeline by `gulp.dest`). But we could make it relative to `file.base` or `file.cwd` which is almost always the root of the project.

**Comment by Toilal** [comment]
I don't think it should be optional, it should just be relative.

To change this base path, just use the base option in gulp.src. Here's my use case

```js
var paths = {
  src: 'src',
  tmp: '.tmp',
}

gulp.task('translate:extract', function () {
  return gulp.src([
    paths.src + '/*.html', paths.src + '/components/**/*.html', paths.src + '/app/**/*.html',
    paths.tmp + '/*.html', paths.tmp + '/components/**/*.html', paths.tmp + '/app/**/*.html'
  ], {base: '.'})
    .pipe($.angularGettext.extract('template.pot'))
    .pipe(gulp.dest(paths.src + '/po/'));
});
```
