### ISSUE TITLE
Danish -  "No language header found!"

### ISSUE THREAD

**Issue by Pritts** [gabegorelick/gulp-angular-gettext#30]
I have following header set yet it's not recognised by angular-gettext.
`msgid "" `
`msgstr ""`
`"MIME-Version: 1.0\n"`
`"Content-Type: text/plain; charset=UTF-8\n`
`"Content-Transfer-Encoding: 8bit\n"`
`"X-Generator: POEditor.com\n"`
`"Project-Id-Version: app\n"`
`"Language: da\n"`

The language is Danish.
I'm using gulp-angular-gettext to compile and extract. It might be a gulp-angular-gettext problem, but i'm not sure.

**Comment by gabegorelick** [comment]
If there's an issue, it's probably in angular-gettext-tools. This is a very small wrapper around that.
