### ISSUE TITLE
task unable to find strings solved through ternary operator ( x ? : )

### ISSUE THREAD

**Issue by acabra85** [gabegorelick/gulp-angular-gettext#31]
The **$.gettext.extract** task is unable to populate the strings on the template.pot file, for the following html code.

`<b>{{ checkVar ? ('when_checkVar_true' | translate) : ('when_checkVar_false' | translate) }}</b>`

**Comment by gabegorelick** [comment]
Issues like this should be filed in the angular-gettext repo, since they're not related to the gulp plugin. Thanks.
