### ISSUE TITLE
Extracting text in .pot from javascript file not working

### ISSUE THREAD

**Issue by namig** [gabegorelick/gulp-angular-gettext#36]
Everything works correctly with html file.
I try to extract text from simple js file and it doesn't work. 
For example:
`var exampleString = "<div translate>Not working</div>";
`

**Comment by gabegorelick** [comment]
angular-gettext doesn't extract HTML in JS strings. You can try reporting this at [angular-gettext-tools](https://github.com/rubenv/angular-gettext-tools) to see if they want to support this use case.

Thanks.

**Comment by namig** [comment]
But what is it?
![2016-10-04_182925](https://cloud.githubusercontent.com/assets/11363626/19080774/d4068db0-8a60-11e6-9523-1957b9d95f41.png)

**Comment by gabegorelick** [comment]
https://angular-gettext.rocketeer.be/dev-guide/annotate-js/

**Comment by namig** [comment]
Thank you
