### ISSUE TITLE
When running in one-pot-per-input-file mode, strings from input file A also appear in pot file B

### ISSUE THREAD

**Issue by mattbrunetti** [gabegorelick/gulp-angular-gettext#37]
When running in one-pot-per-input-file mode, strings from input file A also appear in pot file B.

Example:

if..
- Input file A contains "foo" and "bar"
- Input file B contains "baz"

then..
- Output file A contains "foo" and "bar"
- **Output file B contains "foo", "bar", and "baz"**

**Comment by gabegorelick** [comment]
This should be fixed in v2.3.0. Let me know if you have any issues.
