### ISSUE TITLE
Update angular-gettext-tools version to support TypeScript

### ISSUE THREAD

**Issue by rmcc13** [gabegorelick/gulp-angular-gettext#41]
The angular-gettext-tools team recently [added TypeScript support](https://github.com/rubenv/angular-gettext-tools/pull/166) for extraction. Is there any plan to update this gulp-angular-gettext to get these latest changes and support TypeScript as well?

**Comment by gabegorelick** [comment]
This should work fine. angular-gettext-tools is currently at v2.5.0, which is within the semver range that gulp-angular-gettext supports. You may need to update your resolved dependencies to pull in a newer version of angular-gettext-tools, but no changes should be needed in gulp-angular-gettext.

I'm happy to look at PRs, but I have no plans for TS support natively in gulp-angular-gettext.
