### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by nightwolf13** [gabegorelick/gulp-angular-gettext#42]
Hi,
I've tried to install gul-angular-gettext to my project. But when i wrote 
var gettext = require('gulp-angular-gettext');
in my gulpfile.js, i've got this error.
I use nodejs 4.4.5...

**Comment by gabegorelick** [comment]
There was probably something wrong in your code. Closing out this old issue. Hopefully you've solved it.
