### ISSUE TITLE
gulp-util is deprecated, consider replacing it to support Gulp v4

### ISSUE THREAD

**Issue by JorgeAndd** [gabegorelick/gulp-angular-gettext#44]
gulp-angular-text is using gulp-util, which is deprecated. 
gutil.File and gutil.PluginError should be replace.

> gutil.File => https://www.npmjs.com/package/vinyl
> gutil.PluginError => https://www.npmjs.com/package/plugin-error

For more information
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by gabegorelick** [comment]
Fixed in #52. Thanks!

**Comment by gabegorelick** [comment]
This should be fixed in v2.3.0. Let me know if you have any issues.
