### ISSUE TITLE
Broken lodash.isstring dependency version

### ISSUE THREAD

**Issue by doctorlard** [gabegorelick/gulp-angular-gettext#47]
The security fix on PR #45 broke the `lodash.isstring` version. Latest version is 4.0.1, which doesn't constrain builds to lodash < 4.17.5 as far as I can tell. Would it make sense to depend on `lodash` instead of `lodash.isstring` given that `angular-gettext-tools` and `eslint` already depend on it?

**Comment by gabegorelick** [comment]
Fixed in https://github.com/gabegorelick/gulp-angular-gettext/pull/51.

**Comment by gabegorelick** [comment]
This should be fixed in v2.3.0. Let me know if you have any issues.
